services:
  express:
    build:
      context: ./express
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:3001:3001

    container_name: express

  postgres:
    image: postgres:14-alpine
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - database:/var/lib/postgresql/data

    container_name: postgres

    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb

  next:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:qwerty@postgres:5432/mydb?schema=public
      EXPRESS_URL: http://express:3001

    ports:
      - 3000:3000
    container_name: next

volumes:
  database:
